//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fondos_Antiguos.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CatalogoRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogoRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fondos_Antiguos.Localization.CatalogoRes", typeof(CatalogoRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string Año {
            get {
                return ResourceManager.GetString("Año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string btnCrear {
            get {
                return ResourceManager.GetString("btnCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Serie....
        /// </summary>
        public static string btnSeleccionarSerie {
            get {
                return ResourceManager.GetString("btnSeleccionarSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido.
        /// </summary>
        public static string Contenido {
            get {
                return ResourceManager.GetString("Contenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Ingreso.
        /// </summary>
        public static string FechaIngreso {
            get {
                return ResourceManager.GetString("FechaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichero.
        /// </summary>
        public static string Fichero {
            get {
                return ResourceManager.GetString("Fichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        public static string Folio {
            get {
                return ResourceManager.GetString("Folio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caja {0}.
        /// </summary>
        public static string FormatoCajaSignatura {
            get {
                return ResourceManager.GetString("FormatoCajaSignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpeta {0}.
        /// </summary>
        public static string FormatoCarpetaSignatura {
            get {
                return ResourceManager.GetString("FormatoCarpetaSignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expediente {0}.
        /// </summary>
        public static string FormatoExpedienteSignatura {
            get {
                return ResourceManager.GetString("FormatoExpedienteSignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string FormatoFicheroSignatura {
            get {
                return ResourceManager.GetString("FormatoFicheroSignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string FormatoFolioSignatura {
            get {
                return ResourceManager.GetString("FormatoFolioSignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libro {0}.
        /// </summary>
        public static string FormatoLibroSignatura {
            get {
                return ResourceManager.GetString("FormatoLibroSignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomo {0}.
        /// </summary>
        public static string FormatoTomoSignatura {
            get {
                return ResourceManager.GetString("FormatoTomoSignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Tabla.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Serie.
        /// </summary>
        public static string IdSerie {
            get {
                return ResourceManager.GetString("IdSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo UNA.
        /// </summary>
        public static string IncluirHistVal0 {
            get {
                return ResourceManager.GetString("IncluirHistVal0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambos catálogos.
        /// </summary>
        public static string IncluirHistVal1 {
            get {
                return ResourceManager.GetString("IncluirHistVal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo AHABAT.
        /// </summary>
        public static string IncluirHistVal2 {
            get {
                return ResourceManager.GetString("IncluirHistVal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libro.
        /// </summary>
        public static string Libro {
            get {
                return ResourceManager.GetString("Libro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar.
        /// </summary>
        public static string Lugar {
            get {
                return ResourceManager.GetString("Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materias.
        /// </summary>
        public static string Materias {
            get {
                return ResourceManager.GetString("Materias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        public static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Caja.
        /// </summary>
        public static string NumCaja {
            get {
                return ResourceManager.GetString("NumCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Carpeta.
        /// </summary>
        public static string NumCarpeta {
            get {
                return ResourceManager.GetString("NumCarpeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Expediente.
        /// </summary>
        public static string NumExpediente {
            get {
                return ResourceManager.GetString("NumExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Tomo.
        /// </summary>
        public static string NumTomo {
            get {
                return ResourceManager.GetString("NumTomo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Registro agregado!.
        /// </summary>
        public static string RegistroAgregadoMsg {
            get {
                return ResourceManager.GetString("RegistroAgregadoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Registro borrado!.
        /// </summary>
        public static string RegistroBorradoMsg {
            get {
                return ResourceManager.GetString("RegistroBorradoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Registro no existe!.
        /// </summary>
        public static string RegistroNoExisteError {
            get {
                return ResourceManager.GetString("RegistroNoExisteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string SeriesNombre {
            get {
                return ResourceManager.GetString("SeriesNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatura.
        /// </summary>
        public static string Signatura {
            get {
                return ResourceManager.GetString("Signatura", resourceCulture);
            }
        }
    }
}
