//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fondos_Antiguos.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComunResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComunResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fondos_Antiguos.Localization.ComunResource", typeof(ComunResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string btnAgregar {
            get {
                return ResourceManager.GetString("btnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Nuevo.
        /// </summary>
        public static string btnAgregarNuevo {
            get {
                return ResourceManager.GetString("btnAgregarNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string btnBorrar {
            get {
                return ResourceManager.GetString("btnBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string btnEditar {
            get {
                return ResourceManager.GetString("btnEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir.
        /// </summary>
        public static string btnElegir {
            get {
                return ResourceManager.GetString("btnElegir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva.
        /// </summary>
        public static string btnNueva {
            get {
                return ResourceManager.GetString("btnNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string btnNuevo {
            get {
                return ResourceManager.GetString("btnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string btnSi {
            get {
                return ResourceManager.GetString("btnSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string btnVer {
            get {
                return ResourceManager.GetString("btnVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Para listar multiples valores, utilizar &quot;|&quot; como separador de lista..
        /// </summary>
        public static string LeyendaFiltroMultiValor {
            get {
                return ResourceManager.GetString("LeyendaFiltroMultiValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Volver a lista.
        /// </summary>
        public static string lnkVolverALista {
            get {
                return ResourceManager.GetString("lnkVolverALista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay {0} en la lista..
        /// </summary>
        public static string NoHayEnLaListaFmtMsg {
            get {
                return ResourceManager.GetString("NoHayEnLaListaFmtMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación.
        /// </summary>
        public static string Operacion {
            get {
                return ResourceManager.GetString("Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diferente A.
        /// </summary>
        public static string OperacionEnum_0 {
            get {
                return ResourceManager.GetString("OperacionEnum.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igual A.
        /// </summary>
        public static string OperacionEnum_1 {
            get {
                return ResourceManager.GetString("OperacionEnum.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igual o Menor que.
        /// </summary>
        public static string OperacionEnum_16 {
            get {
                return ResourceManager.GetString("OperacionEnum.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayor Que.
        /// </summary>
        public static string OperacionEnum_2 {
            get {
                return ResourceManager.GetString("OperacionEnum.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre (Exclusivo).
        /// </summary>
        public static string OperacionEnum_32 {
            get {
                return ResourceManager.GetString("OperacionEnum.32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menor Que.
        /// </summary>
        public static string OperacionEnum_4 {
            get {
                return ResourceManager.GetString("OperacionEnum.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre (Inclusivo).
        /// </summary>
        public static string OperacionEnum_64 {
            get {
                return ResourceManager.GetString("OperacionEnum.64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igual o Mayor que.
        /// </summary>
        public static string OperacionEnum_8 {
            get {
                return ResourceManager.GetString("OperacionEnum.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diferente A.
        /// </summary>
        public static string OperacionEnum_String_0 {
            get {
                return ResourceManager.GetString("OperacionEnum.String.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igual A.
        /// </summary>
        public static string OperacionEnum_String_1 {
            get {
                return ResourceManager.GetString("OperacionEnum.String.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contiene.
        /// </summary>
        public static string OperacionEnum_String_32 {
            get {
                return ResourceManager.GetString("OperacionEnum.String.32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contiene.
        /// </summary>
        public static string OperacionEnum_String_64 {
            get {
                return ResourceManager.GetString("OperacionEnum.String.64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string OperacionFecha {
            get {
                return ResourceManager.GetString("OperacionFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar.
        /// </summary>
        public static string OperacionLugar {
            get {
                return ResourceManager.GetString("OperacionLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia.
        /// </summary>
        public static string OperacionMateria {
            get {
                return ResourceManager.GetString("OperacionMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string OperacionSerie {
            get {
                return ResourceManager.GetString("OperacionSerie", resourceCulture);
            }
        }
    }
}
