//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fondos_Antiguos.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HtmlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fondos_Antiguos.Localization.HtmlResource", typeof(HtmlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=&quot;rowLugar{0}&quot;&gt;&lt;td class=&quot;col-11&quot;&gt; &lt;input data-val=&quot;true&quot; data-val-number=&quot;The field Estado must be a number.&quot;  data-val-required=&quot;The Estado field is required.&quot;  id=&quot;EstadoLugar{0}&quot; name=&quot;ListaMaterias[{i}].Estado&quot; type=&quot;hidden&quot; value=&quot;{2}&quot;&gt; &lt;input data-val=&quot;true&quot; data-val-required=&quot;The ID field is required.&quot; id=&quot;ListaLugares_{i}__ID&quot; name=&quot;ListaLugares[{i}].ID&quot; type=&quot;hidden&quot; value=&quot;{0}&quot;&gt;{1}&lt;/td&gt;&lt;td class=&quot;col-1&quot;&gt; &lt;button type=&quot;button&quot; class=&quot;btn btn-outline-danger border-0&quot; aria-label=&quot;Delete&quot; oncli [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CatalogoLugarCrear_NuevoTableRow {
            get {
                return ResourceManager.GetString("CatalogoLugarCrear_NuevoTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=&quot;row{0}&quot;&gt;&lt;td class=&quot;col-11&quot;&gt; &lt;input data-val=&quot;true&quot; data-val-number=&quot;The field Estado must be a number.&quot;  data-val-required=&quot;The Estado field is required.&quot;  id=&quot;EstadoLugar{0}&quot; name=&quot;ListaLugares[{i}].Estado&quot; type=&quot;hidden&quot; value=&quot;{2}&quot;&gt; &lt;input data-val=&quot;true&quot; data-val-required=&quot;The ID field is required.&quot; id=&quot;ListaLugares_{i}__ID&quot; name=&quot;ListaLugares[{i}].ID&quot; type=&quot;hidden&quot; value=&quot;{0}&quot;&gt;{1}&lt;/td&gt;&lt;td class=&quot;col-1&quot;&gt; &lt;button type=&quot;button&quot; class=&quot;btn btn-outline-danger border-0&quot; aria-label=&quot;Delete&quot; onclick=&quot;On [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CatalogoLugarEditar_NuevoTableRow {
            get {
                return ResourceManager.GetString("CatalogoLugarEditar_NuevoTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=&quot;rowMateria{0}&quot;&gt;&lt;td class=&quot;col-11&quot;&gt; &lt;input data-val=&quot;true&quot; data-val-number=&quot;The field Estado must be a number.&quot;  data-val-required=&quot;The Estado field is required.&quot;  id=&quot;EstadoMateria{0}&quot; name=&quot;ListaMaterias[{i}].Estado&quot; type=&quot;hidden&quot; value=&quot;{2}&quot;&gt; &lt;input data-val=&quot;true&quot; data-val-required=&quot;The ID field is required.&quot; id=&quot;ListaMaterias_{i}__ID&quot; name=&quot;ListaMaterias[{i}].ID&quot; type=&quot;hidden&quot; value=&quot;{0}&quot;&gt;{1}&lt;/td&gt;&lt;td class=&quot;col-1&quot;&gt; &lt;button type=&quot;button&quot; class=&quot;btn btn-outline-danger border-0&quot; aria-label=&quot;Delete&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CatalogoMateriaCrear_NuevoTableRow {
            get {
                return ResourceManager.GetString("CatalogoMateriaCrear_NuevoTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=&quot;row{0}&quot;&gt;&lt;td class=&quot;col-11&quot;&gt; &lt;input data-val=&quot;true&quot; data-val-number=&quot;The field Estado must be a number.&quot;  data-val-required=&quot;The Estado field is required.&quot;  id=&quot;EstadoMateria{0}&quot; name=&quot;ListaMateriasSeleccionables[{i}].Estado&quot; type=&quot;hidden&quot; value=&quot;{2}&quot;&gt; &lt;input data-val=&quot;true&quot; data-val-required=&quot;The ID field is required.&quot; id=&quot;ListaMateriasSeleccionables_{i}__ID&quot; name=&quot;ListaMateriasSeleccionables[{i}].ID&quot; type=&quot;hidden&quot; value=&quot;{0}&quot;&gt;{1}&lt;/td&gt;&lt;td class=&quot;col-1&quot;&gt; &lt;button type=&quot;button&quot; class=&quot;btn btn-outline-d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CatalogoMateriaEditar_NuevoTableRow {
            get {
                return ResourceManager.GetString("CatalogoMateriaEditar_NuevoTableRow", resourceCulture);
            }
        }
    }
}
